### ISSUE TITLE
Test Case Specification

### ISSUE THREAD

**Issue by xrenegade100** [xrenegade100/ProjectSunshine#13]
Add Test Case Specification as Test Plan's attachment defining test cases for unit testing.

**Comment by xrenegade100** [comment]
In review by @BraindeadHermit

**Comment by BraindeadHermit** [comment]
Review completed 💯! all changes are in the [test/resolve-test-smells](https://github.com/xrenegade100/ProjectSunshine/tree/test/resolve-test-smells) branch
