### ISSUE TITLE
[CONTAINERIZATION]: dockefile not working

### ISSUE THREAD

**Issue by antgioia** [xrenegade100/ProjectSunshine#22]
![Immagine WhatsApp 2023-09-04 ore 21 49 31](https://github.com/xrenegade100/ProjectSunshine/assets/63403031/7edc561f-3f2b-4656-a34c-127722c1be27)

**Comment by xrenegade100** [comment]
https://sonarcloud.io/organizations/xrenegade100/rules?open=docker%3AS6500&rule_key=docker%3AS6500 False positive caused this to happen.
