### ISSUE TITLE
[refactor] remove unused variables in src.rule

### ISSUE THREAD

**Issue by xrenegade100** [xrenegade100/ProjectSunshine#49]
Remove the unused private attribute `__project` from those files:

attribute_name_type_opposite.py
attribute_signature_comment_opposite.py
contains_only_special_characters.py
get_more_than_accessor.py
starts_with_special_character.py

**Comment by BraindeadHermit** [comment]
After the changes made to the code, the `__project` variable is found within the parent class `LinguisticAntipattern,` from which all the classes of the **rule** package inherit; removing this variable from the specified classes would mean removing it from the parent class and inserting it only in the various subclasses in which it is used .
Given that there are only 5 classes in which it is superfluous, compared to the 24 present, is it worth carrying out this operation?

**Comment by BraindeadHermit** [comment]
In the end in the specified classes it was decided to use the `public` variable and not the `private` one, code smells have been resolved 💯
